version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_PORT=11434

  open-webui:
    image: linuxserver/open-webui:latest
    depends_on:
      - ollama
    ports:
      - "8080:80"
