services:
  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    container_name: mychatbot_openwebui
    hostname: openwebui
    restart: unless-stopped
    volumes:
      - ./open-webui-local:/app/backend/data:z
    ports:
      - "8080:8080"
    environment:
      OLLAMA_BASE_URLS: http://ollama:11434

  ollama:
    image: ollama/ollama:rocm
    container_name: mychatbot_ollama
    hostname: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-local:/root/.ollama:z
